apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namespace: uat-applications
patchesStrategicMerge:
- 01-deployment.yaml
- 02-service.yaml
#- 03-ingress.yaml
patchesJSON6902:
- patch: |-
   - op: replace
     path: /metadata/name
     value: uat-ingress-gateway
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: dev-ingress-gateway