apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: build-bot-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: build-bot
type: kubernetes.io/service-account-token
