---
services:
  gateway:
    image: phiroict/training_k8s_rust_gateway:20220806.3
    ports:
    - "8100:8000"
    environment:
    - DATASOURCE_URL=dataset:8010
  dataset:
    image: phiroict/training_k8s_rust_datasource:20220806.3
    ports:
    - "8110:8010"
