apiVersion: apps/v1
kind: Deployment
metadata:
  name:  concourse-worker
  namespace: ci
  labels:
    app:  concourse-worker
spec:
  selector:
    matchLabels:
      app: concourse-worker
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  concourse-worker
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  concourse-worker
        image:  "concourse/concourse:7.8.2-ubuntu-20220725"
        args: ["worker"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 2222
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: CONCOURSE_WORK_DIR
          value: /opt/concourse/worker
        - name: CONCOURSE_TSA_HOST
          value: concourse-web-service:2222
        - name: CONCOURSE_TSA_PUBLIC_KEY
          value: "/opt/hostkeypub/tsa_host_key.pub"
        - name: CONCOURSE_TSA_WORKER_PRIVATE_KEY
          value: "/opt/workerkey/worker_key"
        ports:
        - containerPort:  2222
          name:  con-worker
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: hostkeypub
          mountPath: "/opt/hostkeypub"
          readOnly: true
        - name: workerkeypriv
          mountPath: "/opt/workerkey"
          readOnly: true

      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Pacific/Aucklland
        - name: hostkeypub
          secret:
            secretName: tsa-host-public
            optional: false
        - name: workerkeypriv
          secret:
            secretName: worker-private
            optional: false
      restartPolicy: Always
      