project: default
source:
  repoURL: 'git@github.com:phiroict/training-kube-certification.git'
  path: stack/helm
  targetRevision: HEAD
  helm:
    valueFiles:
      - environments/dev/values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: dev-applications
