---
resources:
- name: gateway-project
  type: git
  source:
    uri: https://github.com/phiroict/training-kube-certification
    branch: main
    username: ((git-username.git-username))
    password: ((git-password.git-password))

- name: rust-builder
  type: registry-image
  source:
    repository: rust
    tag: latest

- name: build-container-repo
  type: registry-image
  icon: docker
  source:
    repository: phiroict/training_k8s_rust_gateway
    tag: latest
    username: ((registry-username.registry-username))
    password: ((registry-password.registry-password))
- name: build-container-ds-repo
  type: registry-image
  icon: docker
  source:
    repository: phiroict/training_k8s_rust_datasource
    tag: latest
    username: ((registry-username.registry-username))
    password: ((registry-password.registry-password))

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/phiroict/training-kube-certification
    branch: main
    file: version
    username: ((git-username.git-username))
    password: ((git-password.git-password))
    initial_version: 20220813.1.0

jobs:
- name: build-ms-gateway
  plan:
  - get: version
  - get: gateway-project
    trigger: false
  - get: rust-builder
    trigger: false
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: gateway-project
      outputs:
      - name: image
      run:
        path: build
      params:
        DOCKERFILE: gateway-project/infra/docker/Dockerfile
        CONTEXT: gateway-project
        BUILD_ARG_app_name: gateway
        BUILD_ARG_path: apps
  - put: build-container-repo
    params:
      image: image/image.tar
      additional_tags: version/version
  - task: set-updated-image

    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: python
      inputs:
      - name: gateway-project
      outputs:
      - name: gateway-project
      run:
        path: bash
        args:
          - "gateway-project/update_build_extension.sh"
          - "gateway-project/stack/kustomize/base/01-deployment.yaml"
          - "app-gateway"
          - "phiroict/training_k8s_rust_gateway:gateway-project/version"
          - "gateway-project"
  - task: commit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: concourse/buildroot
          tag: git
      inputs:
      - name: gateway-project
      outputs:
      - name: gateway-project
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -eux
          cd gateway-project
          git config --global user.name "Concourse builder"
          git config --global user.email "concourse@phiroict.co.nz"
          git status
          git commit -am "Set new buildnumber in deployment gateway app"
  - put: gateway-project
    params:
      repository: gateway-project
      merge: true
#  - put: version
#    params: {file: version/version , bump: minor}

# Job : Build datasource
- name: build-ms-datasource
  plan:
  - get: version
    passed: [build-ms-gateway]
    trigger: true
  - get: gateway-project
    trigger: false
  - get: rust-builder
    trigger: false
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: gateway-project
      outputs:
      - name: image
      run:
        path: build
      params:
        DOCKERFILE: gateway-project/infra/docker/Dockerfile
        CONTEXT: gateway-project
        BUILD_ARG_app_name: datasource
        BUILD_ARG_path: apps
  - task: set-updated-image
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: python
      inputs:
      - name: gateway-project
      outputs:
      - name: gateway-project
      run:
        path: bash
        args:
          - "gateway-project/update_build_extension.sh"
          - "gateway-project/stack/kustomize/base/01-deployment.yaml"
          - "app-datasource"
          - "phiroict/training_k8s_rust_datasource:gateway-project/version"
          - "gateway-project"
  - task: commit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: concourse/buildroot
          tag: git
      inputs:
      - name: gateway-project
      outputs:
      - name: gateway-project
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -eux
          cd gateway-project
          git config --global user.name "Concourse builder"
          git config --global user.email "concourse@phiroict.co.nz"
          git status
          git commit -am "Set new buildnumber in deployment datasource app"
  - put: build-container-ds-repo
    params:
      image: image/image.tar
      additional_tags: version/version
  - put: gateway-project
    params:
      repository: gateway-project
      merge: true
  - put: version
    params: {file: version/version , bump: minor}
- name: set-version-to-the-next
  plan:
  - get: version
    params: {file: version/version , bump: minor}
    passed:
    - build-ms-gateway
    - build-ms-datasource
  - put: version
    params: {file: version/version , bump: minor}