---
resources:
- name: gateway-project
  type: git
  source:
    uri: https://github.com/phiroict/training-kube-certification
    branch: main
    username: ((git-username.git-username))
    password: ((git-password.git-password))

- name: rust-builder
  type: registry-image
  source:
    repository: rust
    tag: latest

- name: build-container-repo
  type: registry-image
  icon: docker
  source:
    repository: phiroict/training_k8s_rust_gateway
    tag: 20220813.1
    username: ((registry-username.registry-username))
    password: ((registry-password.registry-password))
- name: build-container-ds-repo
  type: registry-image
  icon: docker
  source:
    repository: phiroict/training_k8s_rust_datasource
    tag: 20220813.1
    username: ((registry-username.registry-username))
    password: ((registry-password.registry-password))

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/phiroict/training-kube-certification
    branch: main
    file: version
    username: ((git-username.git-username))
    password: ((git-password.git-password))
    initial_version: 20220813.1.0

jobs:
- name: the-gate  # manually trigger this job
  plan:
  - get: gateway-project
    trigger: false
    passed:  # fan-in from the three pre-gate jobs
      - build-ms-gateway
      - build-ms-datasource
- name: build-ms-gateway
  plan:
  - get: version
    params: {bump: minor}
  - get: gateway-project
    trigger: false
  - get: rust-builder
    trigger: false
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: gateway-project
      outputs:
      - name: image
      run:
        path: build
      params:
        DOCKERFILE: gateway-project/infra/docker/Dockerfile
        CONTEXT: gateway-project
        BUILD_ARG_app_name: gateway
        BUILD_ARG_path: apps
  - put: build-container-repo
    params:
      image: image/image.tar
      additional_tags: version/version
  - task: set-updated-image

    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: python
      inputs:
      - name: gateway-project
      outputs:
      - name: gateway-project
      run:
        path: pip
        args:
        - "install"
        - "--no-input"
        - "yaml"
      run:
        path: python
        args:
          - "gateway-project/update_build_extension.py"
          - "gateway-project/stack/kustomize/base/01-deployment.yaml"
          - "app-gateway"
          - "$(cat gateway-project/version)"
  - put: version
    params: {file: version/version , bump: minor}
  - put: gateway-project
- name: build-ms-datasource
  plan:
  - get: version
  - get: gateway-project
    trigger: false
  - get: rust-builder
    trigger: false
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: gateway-project
      outputs:
      - name: image
      run:
        path: build
      params:
        DOCKERFILE: gateway-project/infra/docker/Dockerfile
        CONTEXT: gateway-project
        BUILD_ARG_app_name: datasource
        BUILD_ARG_path: apps
  - put: build-container-ds-repo
    params:
      image: image/image.tar
      additional_tags: version/version
  - put: version
    params: {file: version/version , bump: minor}