---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway-{{ .Values.env }}-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 32000
      name: http
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: gateway-cred-{{ .Values.env }}
    hosts:
    - {{ .Values.env }}.phiroict.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gateway-{{ .Values.env }}-vservice
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ .Values.env }}.phiroict.local
  gateways:
  - gateway-{{ .Values.env }}-gateway
  http:
  - match:
    - port: 8000
    route:
    - destination:
        port:
          number: 8000
        host: gateway
