apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-gateway
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32000
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
